#!/usr/bin/env python3
"""Write a repository's `.github/copilot-instructions.md`, its Copilot guide.

The guide follows rust-workflows' own: where to start, a tree of every
tracked file with a one-line explanation, then how to change and verify.
The tree comes from `git ls-files`. Each explanation is the one the current
guide already gives for that path, so a person can improve any of them; else
the repository README's table row for the path; else what the file says of
itself: a module's first doc line, a Markdown title or first sentence, a
workflow's name, a configuration file's first comment.

Run it from a repository's root; in this workspace:

    python3 ../.github/scripts/copilot-instructions.py [--check]

`--check` writes nothing and exits 1 when the committed guide differs from
what this script renders. Standard library only.
"""

import argparse
import json
import re
import subprocess
import sys
import textwrap
from pathlib import Path

GUIDE = ".github/copilot-instructions.md"
ORG = "https://github.com/Orchestration-Maestro/.github/blob/main"
COLUMN = 48  # where explanations start, as in rust-workflows' guide
SKIPPED_SUFFIXES = (":Zone.Identifier", ".cdx.json")
MANAGED = "generated by rust-gate"
RENDERED = "; rendered by rust-gate sync"
LONGEST = 140
WIDTH = 80
SKIPPED_BLOCKS = ("#", "|", "```", "<", "![", "[![", "- ", "* ", ">")

# Files whose role their name fixes, whatever they contain.
FIXED = {
    "LICENSE": "The licence this repository is distributed under",
    "Cargo.lock": "Exact dependency versions, committed so every build resolves the same",
    "mise.lock": "The checksum of every pinned tool download",
    "CODEOWNERS": "Who reviews each path",
    "AGENTS.md": "Rules for coding agents: what to read, what never to weaken, how to verify",
    "CONTEXT.md": "The words this repository uses, and the ones it avoids",
    "copilot-instructions.md": "This guide, regenerated by the organization's script",
}
# What a file is for when it says nothing of itself.
FALLBACK = {
    ".gitignore": "Paths git never tracks",
    ".pre-commit-config.yaml": "The commit hooks prek runs locally and CI runs over every file",
    ".yamlfmt.yml": "How yamlfmt formats every YAML file",
    "rust-toolchain.toml": "The pinned Rust toolchain",
    "justfile": "The local gate, just check, and every developer recipe",
    "mise.toml": "The pinned toolbelt, installed by scripts/bootstrap.sh",
    "version.txt": "The released version, which release-please moves",
    "imports.lock": "The audits cargo-vet imports, locked",
}
# Path parts under which a Markdown file is sample content, not documentation.
SAMPLES = {"examples", "expected", "fixtures", "testdata"}
BY_DIRECTORY = {
    ".github": "GitHub metadata, templates and workflows",
    ".github/workflows": "GitHub Actions workflows",
    ".github/ISSUE_TEMPLATE": "Issue forms and the chooser",
    ".github/skills": "Agent skills",
    ".cargo": "Cargo settings for this workspace",
    ".config": "Tool settings that live in a directory",
    ".specify": "Spec Kit's templates, scripts and workflows",
    "assets": "Images and other assets",
    "bin": "Binaries, one file per executable",
    "expected": "What the tool must write for the example input",
    "plans": "Implementation plans",
    "profile/foundations": "The foundation cards on the organization page",
    "profile/pillars": "The four pillar icons on the organization page",
    "crates": "The workspace's crates",
    "docs": "Documentation",
    "docs/adr": "Architecture decision records",
    "examples": "Worked examples",
    "fixtures": "Test fixtures",
    "org": "The organization's live settings, as scripts/export-org.py exports them",
    "org/rulesets": "Organization rulesets, in the shape the API accepts",
    "profile": "The organization page on GitHub",
    "scripts": "Maintenance scripts",
    "specs": "Specifications, one directory per slice",
    "src": "The crate's sources",
    "supply-chain": "cargo-vet audits, configuration and imports",
    "tests": "Integration tests",
    "workflow-templates": "Workflow templates offered under Actions, New workflow",
}
KIND = {
    ".json": "JSON data", ".svg": "SVG image", ".png": "PNG image", ".jpg": "JPEG image",
    ".jpeg": "JPEG image", ".webp": "WebP image", ".gif": "GIF image", ".txt": "Text",
    ".sh": "Shell script", ".py": "Python script", ".rs": "Rust source", ".md": "Document",
    ".yml": "YAML settings", ".yaml": "YAML settings", ".toml": "TOML settings",
}


def tracked(root):
    """Every tracked file, and this guide, as sorted relative paths."""
    listed = subprocess.run(
        ["git", "-C", str(root), "ls-files", "-z"], capture_output=True, check=True
    ).stdout.decode().split("\0")
    paths = {p for p in listed if p and not p.endswith(SKIPPED_SUFFIXES)}
    paths.add(GUIDE)
    return sorted(paths)


def sentence(text):
    """The first sentence of `text`, on one line, at most LONGEST characters."""
    text = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", text)
    text = re.sub(r"\s+", " ", re.sub(r"`|\*\*", "", text)).strip()
    text = re.split(r"(?<=[.!?])\s", text, maxsplit=1)[0].strip()
    if len(text) > LONGEST:
        cut = text[:LONGEST]
        clause = max(cut.rfind(", "), cut.rfind("; "), cut.rfind(": "))
        text = cut[:clause] if clause > LONGEST // 2 else cut.rsplit(" ", 1)[0]
    return text.rstrip(".,;: ")


def managed(text):
    """Whether `rust-gate sync` writes this file."""
    return MANAGED in "\n".join(text.splitlines()[:5])


def first_comment(text):
    """The first comment block that says something, as one sentence."""
    block = []
    for line in text.splitlines()[:60]:
        stripped = line.strip()
        is_comment = stripped.startswith(("#", "//")) and not stripped.startswith("#!")
        body = stripped.lstrip("#/").strip() if is_comment else ""
        if is_comment and (MANAGED in body or "do not edit" in body.lower()):
            continue
        if is_comment and body and not body.startswith(("yaml-language-server", "shellcheck")):
            block.append(body)
        elif block:
            break
    return sentence(" ".join(block)) if block else ""


def markdown(text, path):
    """A Markdown file's front-matter description, its title, or its first sentence."""
    front = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if front:
        described = re.search(r"^description:\s*[\"']?(.+?)[\"']?\s*$", front.group(1), re.M)
        if described:
            return sentence(described.group(1))
        text = text[front.end():]
    title = re.search(r"^#\s+(.+)$", text, re.M)
    if SAMPLES & set(path.parts) and path.name != "README.md":
        return f"Sample document: {sentence(title.group(1)) if title else path.stem}"
    if path.name != "README.md" and title and title.group(1).strip("` ").lower() != path.stem.lower():
        return sentence(title.group(1))
    return paragraph(text) or (sentence(title.group(1)) if title else "")


def paragraph(text):
    """The first sentence of the first prose paragraph."""
    for block in re.split(r"\n\s*\n", text):
        block = block.strip()
        if block and not block.startswith(SKIPPED_BLOCKS):
            return sentence(block)
    return ""


def yaml(text, path):
    """A workflow's name and what it calls, a form's description, else a comment."""
    name = re.search(r"^name:\s*[\"']?(.+?)[\"']?\s*$", text, re.M)
    if name and re.search(r"^\"?on\"?:", text, re.M) and re.search(r"^jobs:", text, re.M):
        called = sorted(set(re.findall(r"uses:\s*[^\s@]*/\.github/workflows/([\w.-]+)@", text)))
        return f"{name.group(1)}: calls {', '.join(called)}" if called else name.group(1)
    if "ISSUE_TEMPLATE" in path.parts:
        described = re.search(r"^description:\s*[\"']?(.+?)[\"']?\s*$", text, re.M)
        if described:
            return sentence(described.group(1))
    return first_comment(text) or (name.group(1) if name else "")


def data(text):
    """A JSON file's ruleset, description or name."""
    try:
        value = json.loads(text)
    except ValueError:
        return ""
    if not isinstance(value, dict):
        return ""
    if isinstance(value.get("rules"), list) and isinstance(value.get("name"), str):
        kinds = sorted({rule.get("type", "?") for rule in value["rules"] if isinstance(rule, dict)})
        return sentence(f"Ruleset {value['name']}: {', '.join(kinds)}")
    for key in ("description", "name"):
        if isinstance(value.get(key), str) and value[key].strip():
            return sentence(value[key])
    return ""


def cargo(text):
    """A manifest's package description, or what the workspace holds."""
    described = re.search(r"^description\s*=\s*\"(.+)\"", text, re.M)
    if described:
        return f"Crate manifest: {sentence(described.group(1))}"
    if re.search(r"^\[workspace\]", text, re.M):
        return "Workspace manifest: its members and the lints every member inherits"
    return "Crate manifest"


def describe_file(root, relative):
    """What a file says of itself, or what its name and kind say."""
    path = Path(relative)
    try:
        text = (root / relative).read_text(encoding="utf-8", errors="ignore")[:20000]
    except OSError:
        text = ""
    found = FIXED.get(path.name, "")
    if found:
        pass
    elif path.suffix == ".rs":
        doc = re.search(r"^//!\s*(.+)$", text, re.M)
        found = sentence(doc.group(1)) if doc else ""
    elif path.suffix == ".py":
        doc = re.search(r'^\s*(?:#[^\n]*\n)*\s*[rR]?"""\s*(.+?)(?:\n\s*\n|""")', text, re.S)
        found = sentence(doc.group(1)) if doc else first_comment(text)
    elif path.suffix in (".md", ".mdx"):
        found = markdown(text, path)
    elif path.suffix in (".yml", ".yaml"):
        found = yaml(text, path)
    elif path.suffix == ".json":
        found = data(text)
    elif path.name == "Cargo.toml":
        found = cargo(text)
    elif path.suffix in (".toml", ".sh", "") or path.name.startswith("."):
        found = first_comment(text)
    if not found:
        words = path.stem.replace("-", " ").replace("_", " ").strip(". ")
        found = FALLBACK.get(path.name) or f"{KIND.get(path.suffix, 'File')}: {words or path.name}"
    return found + (RENDERED if managed(text) and RENDERED not in found else "")


def describe_directory(root, relative, tables):
    """A directory's row in the README, its own README, or its usual role."""
    if f"{relative}/" in tables:
        return tables[f"{relative}/"]
    readme = root / relative / "README.md"
    if readme.is_file():
        found = paragraph(readme.read_text(encoding="utf-8", errors="ignore"))
        if found:
            return found
    # A Rust module's doc: in its mod.rs, or in the file beside the directory.
    for module in (root / relative / "mod.rs", (root / relative).with_suffix(".rs")):
        if module.is_file():
            doc = re.search(r"^//!\s*(.+)$", module.read_text(encoding="utf-8", errors="ignore"),
                            re.M)
            if doc:
                return sentence(doc.group(1))
    name = Path(relative).name
    return BY_DIRECTORY.get(relative) or BY_DIRECTORY.get(name) or \
        name.replace("-", " ").replace("_", " ").capitalize()


def readme_rows(root, paths):
    """Descriptions READMEs give paths in their tables, `| path | what it is |`,
    relative to each README; the root README's win."""
    rows = {}
    readmes = sorted((p for p in paths if Path(p).name == "README.md"),
                     key=lambda p: p.count("/"))
    for readme in readmes:
        base = Path(readme).parent
        text = (root / readme).read_text(encoding="utf-8", errors="ignore")
        for match in re.finditer(r"^\|\s*`([^`|]+)`\s*\|\s*([^|]+?)\s*\|", text, re.M):
            named = (base / match.group(1).strip()).as_posix().removeprefix("./")
            rows.setdefault(named + ("/" if match.group(1).strip().endswith("/") else ""),
                            sentence(match.group(2)))
    rows.update({path: alt for path, alt in image_alts(root, paths).items() if path not in rows})
    return rows


def image_alts(root, paths):
    """Each image's alternative text, from the Markdown that shows it: `![alt](src)`,
    or an `<img>` tag whose `src` is relative or a raw URL of this repository."""
    found = {}
    for page in (p for p in paths if p.endswith(".md") and (root / p).is_file()):
        text = (root / page).read_text(encoding="utf-8", errors="ignore")
        pairs = [(m.group(2), m.group(1)) for m in re.finditer(r"!\[([^\]]+)\]\(([^)\s]+)", text)]
        for tag in re.findall(r"<img\b[^>]*>", text):
            source = re.search(r'\bsrc="([^"]+)"', tag)
            alt = re.search(r'\balt="([^"]+)"', tag)
            if source and alt:
                pairs.append((source.group(1), alt.group(1)))
        for source, alt in pairs:
            if "://" in source:
                if "/main/" not in source:
                    continue
                path = source.split("/main/", 1)[1]
            else:
                path = (Path(page).parent / source).as_posix().removeprefix("./")
            if path in paths:
                found.setdefault(path, sentence(alt))
    return found


def kept(guide):
    """The explanations the current guide gives, by path, '.' for the root."""
    block = re.search(r"```text\n(.*?)```", guide, re.S)
    found, stack = {}, []
    for line in (block.group(1).splitlines() if block else []):
        entry, _, description = line.partition("  # ")
        entry = entry.rstrip()
        if entry == ".":
            found["."] = description.strip()
            continue
        shape = re.match(r"^((?:│   |    )*)(?:├── |└── )(.+)$", entry)
        if not shape or not description.strip():
            continue
        depth, name = len(shape.group(1)) // 4, shape.group(2)
        stack = stack[:depth]
        found["/".join([*stack, name.rstrip("/")])] = description.strip()
        if name.endswith("/"):
            stack.append(name.rstrip("/"))
    return found


def tree_lines(root, paths, previous, tables):
    """The annotated tree: directories first, then files, each sorted by name."""
    nested = {}
    for path in paths:
        node = nested
        for part in path.split("/")[:-1]:
            node = node.setdefault(part + "/", {})
        node[path.split("/")[-1]] = None
    entries = [(".", previous.get(".", "Repository root"))]

    def walk(node, prefix, parents):
        names = sorted(node, key=lambda n: (not n.endswith("/"), n.rstrip("/")))
        for index, name in enumerate(names):
            last = index + 1 == len(names)
            relative = "/".join([*parents, name.rstrip("/")])
            if name.endswith("/"):
                text = previous.get(relative) or describe_directory(root, relative, tables)
            else:
                text = previous.get(relative) or tables.get(relative) \
                    or describe_file(root, relative)
            entries.append((f"{prefix}{'└── ' if last else '├── '}{name}", text))
            if name.endswith("/"):
                walk(node[name], prefix + ("    " if last else "│   "),
                     [*parents, name.rstrip("/")])

    walk(nested, "", [])
    width = max(COLUMN, max(len(entry) + 2 for entry, _ in entries))
    return [f"{entry.ljust(width)}# {text}" for entry, text in entries]


def community(root, name):
    """The relative link to the repository's own community file, or the default's URL."""
    for place in ("", ".github/", "docs/"):
        if (root / place / name).is_file():
            return f"../{place}{name}"
    return f"{ORG}/{name}"


def purpose(root):
    """What the repository is: its README's first prose paragraph, whole."""
    readme = root / "README.md"
    if not readme.is_file():
        return ""
    text = re.sub(r"^#.*$", "", readme.read_text(encoding="utf-8"), count=1, flags=re.M)
    for block in re.split(r"\n\s*\n", text):
        block = block.strip()
        if block and not block.startswith(SKIPPED_BLOCKS):
            # The README's relative links resolve from the root; this guide is in .github/.
            block = re.sub(r"\]\((?![a-z][a-z+.-]*:|/|#)([^)]+)\)", r"](../\1)", block)
            return re.sub(r"\s*\n\s*", " ", block)
    return ""


def gate(root):
    """The command that runs this repository's checks before a commit."""
    justfile = root / "justfile"
    if justfile.is_file() and re.search(r"^check\b", justfile.read_text(encoding="utf-8"), re.M):
        bootstrap = (root / "scripts/bootstrap.sh").is_file()
        return ("`scripts/bootstrap.sh` once, then " if bootstrap else "") + "`just check`"
    return "`prek run --all-files`"


def prose(text, indent=""):
    """A paragraph wrapped at WIDTH columns, continuation lines indented."""
    return textwrap.fill(text, WIDTH, subsequent_indent=indent, break_on_hyphens=False,
                         break_long_words=False)


def render(root):
    """The guide this script writes for the repository at `root`."""
    guide = root / GUIDE
    previous = kept(guide.read_text(encoding="utf-8")) if guide.is_file() else {}
    paths = tracked(root)
    readme = root / "README.md"
    title = re.search(r"^#\s+(.+)$", readme.read_text(encoding="utf-8"), re.M) \
        if readme.is_file() else None
    name = title.group(1).strip() if title else root.resolve().name
    reads = ["[AGENTS.md](../AGENTS.md) for the rules that bind every change"]
    if (root / "CONTEXT.md").is_file():
        reads.append("[CONTEXT.md](../CONTEXT.md) for the words it uses")
    reads.append(f"[CONTRIBUTING.md]({community(root, 'CONTRIBUTING.md')}) for how a "
                 "change is proposed")
    standards = [f"[{page}](../docs/standards/{page})"
                 for page in ("northstar.md", "engineering.md", "security.md")
                 if (root / "docs/standards" / page).is_file()]
    rules = ("For quality, engineering or security changes, read "
             + (", ".join(standards[:-1]) + " and " if len(standards) > 1 else "")
             + f"{standards[-1]}: this repository's map of the organization's golden "
             "rules.") if standards else ""
    steps = [
        "Read the rules in AGENTS.md that cover the files you change, and keep every "
        "gate intact: never weaken one to pass.",
        "Add an executable regression check for a change in behaviour.",
        "After adding, moving or removing a file, run "
        "`python3 ../.github/scripts/copilot-instructions.py` from the repository root "
        "and commit this guide; the organization's daily drift check fails while it is "
        "stale.",
        f"Run {gate(root)}, and report the commands you actually ran.",
        "Commits are signed, with a conventional title; the default branch takes only "
        "squash-merged pull requests.",
    ]
    lines = [
        f"# Copilot instructions for {name}",
        "",
        "## Start here",
        "",
        prose(purpose(root) or f"The {name} repository."),
        "",
        prose("Paths below are relative to this repository. Before editing, read "
              + ", ".join(reads[:-1]) + f" and {reads[-1]}. The organization's "
              f"[constitution]({ORG}/CONSTITUTION.md) binds every specification, plan, "
              "review and release."),
        "",
        *([prose(rules), ""] if rules else []),
        prose("Keep changes scoped to the request, and read historical plans and "
              "specifications as records, not as instructions to start new work."),
        "",
        "## Repository tree",
        "",
        prose("Every tracked file, with what it is for. The organization's "
              "`scripts/copilot-instructions.py` writes this tree and keeps each "
              "explanation already here, so improve an explanation in place."),
        "",
        "```text",
        *tree_lines(root, paths, previous, readme_rows(root, paths)),
        "```",
        "",
        "## Change and verification procedure",
        "",
        *(prose(f"{number}. {step}", "   ") for number, step in enumerate(steps, 1)),
        "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Write a repository's Copilot guide.")
    parser.add_argument("--check", action="store_true", help="write nothing; exit 1 when stale")
    parser.add_argument("--root", default=".", help="the repository's root (default: .)")
    arguments = parser.parse_args()
    root = Path(arguments.root)
    text = render(root)
    guide = root / GUIDE
    current = guide.read_text(encoding="utf-8") if guide.is_file() else ""
    if arguments.check:
        if current != text:
            sys.exit(f"{GUIDE} is stale: run scripts/copilot-instructions.py and commit it")
        print(f"{GUIDE} is current")
        return
    guide.parent.mkdir(parents=True, exist_ok=True)
    guide.write_text(text, encoding="utf-8")
    print(f"wrote {GUIDE}: {len(text.splitlines())} lines")


if __name__ == "__main__":
    main()
