#!/usr/bin/env python3
"""Write the gate rules block of the organization page, profile/README.md.

The rules the shared CI refuses are one list in rust-workflows, which
`rust-gate gate-rules` prints: the ID, a short name, whether a repository may
take an exception, and what the rule holds. This script renders the block
between the page's generated markers from that list, so a rule the gate gains
reaches the page with the release that brings it; quality-sync.py runs it at
every release, and repository-drift.py runs `--check`.

Run it from this repository's root, with `rust-gate` on the PATH:

    python3 scripts/gate-rules.py [--check] [--root DIR]

A root without profile/README.md has no block, and nothing is done. `--check`
writes nothing and exits 1 when the block differs from what the list renders.
Standard library only.
"""

import argparse
import subprocess
import sys
from pathlib import Path

PAGE = Path("profile/README.md")
BEGIN = "<!-- generated by scripts/gate-rules.py from rust-gate gate-rules -->"
END = "<!-- end generated -->"
ONES = (
    "zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten",
    "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen",
    "eighteen", "nineteen",
)
TENS = ("", "", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety")


def in_words(count):
    """`count`, under a hundred, in English words: 34 is "thirty-four"."""
    if count < 20:
        return ONES[count]
    tens, ones = divmod(count, 10)
    return TENS[tens] + (f"-{ONES[ones]}" if ones else "")


def listed_rules():
    """The gate's rules: (ID, name, takes an exception, what it holds)."""
    listing = subprocess.run(["rust-gate", "gate-rules"], capture_output=True,
                             text=True, check=True).stdout
    rules = []
    for line in listing.splitlines():
        rule, name, kind, holds = line.split("\t")
        rules.append((rule, name, kind == "exception", holds))
    return rules


def block(rules):
    """The block between the markers, markers included."""
    excepted = [rule for rule, _, exception, _ in rules if exception]
    named = ", ".join(excepted[:-1]) + f" and {excepted[-1]}" if len(excepted) > 1 else "".join(excepted)
    rows = "\n".join(f"| **{name}**<br>`{rule}` | {holds} |" for rule, name, _, holds in rules)
    return "\n".join([
        BEGIN,
        "<details>",
        f"<summary><strong>{in_words(len(rules)).capitalize()} gate rules</strong>: what the "
        "shared CI refuses on every pull request, most of them already at commit</summary>",
        "",
        "| Rule | In one line |",
        "| --- | --- |",
        rows,
        "",
        f"Only {named} take an exception,",
        "recorded with its reason in the repository's `maestro-quality.toml`; an",
        "exception that stops being true fails the check.",
        "",
        "</details>",
        END,
    ])


def main():
    parser = argparse.ArgumentParser(
        description="Write the gate rules block of the organization page."
    )
    parser.add_argument("--check", action="store_true", help="write nothing; exit 1 when stale")
    parser.add_argument("--root", type=Path, default=Path("."), help="the repository's root")
    arguments = parser.parse_args()
    page = arguments.root / PAGE
    if not page.is_file():
        return
    text = page.read_text()
    start, end = text.find(BEGIN), text.find(END)
    if start < 0 or end < start:
        sys.exit(f"{PAGE}: no gate rules markers; put `{BEGIN}` and `{END}` around the block")
    rendered = text[:start] + block(listed_rules()) + text[end + len(END):]
    if arguments.check:
        if rendered != text:
            sys.exit(f"{PAGE}: the gate rules block is stale; run scripts/gate-rules.py")
        return
    if rendered != text:
        page.write_text(rendered)
        print(f"wrote {PAGE}")


if __name__ == "__main__":
    main()
