#!/usr/bin/env python3
"""Write every generated block of the organization page, profile/README.md.

Each block has one source, and only this script copies it onto the page:

- northstar: golden-rules/northstar.md, its motto, opening paragraph and pillars
- foundations, mandates, principles: golden-rules/engineering.md
- security: golden-rules/security.md
- gate-rules: rust-workflows' list, as `rust-gate gate-rules` prints it
- standards: golden-rules/standards.md
- repositories: the description each public repository shows on GitHub

It refuses golden rules that disagree with themselves first: a count in words
that is not the number of rules, a rule without its `>` summary, a standard a
rule maps that golden-rules/standards.md does not list, a missing picture.
quality-sync.py runs it whenever a source changes and at every release, and
repository-drift.py runs `--check`.

Run it from this repository's root, with `rust-gate` on the PATH and `gh`
signed in:

    python3 scripts/org-page.py [--check] [--root DIR]

`--check` writes nothing and exits 1 when a block differs from its source. A
root without profile/README.md has no page, and nothing is done. Standard
library only.
"""

import argparse
import json
import re
import subprocess
import sys
import textwrap
from pathlib import Path

ORG = "Orchestration-Maestro"
PAGE = Path("profile/README.md")
RULES = Path("golden-rules")
RAW = f"https://raw.githubusercontent.com/{ORG}/.github/main/"
BLOB = f"https://github.com/{ORG}/.github/blob/main/"
BEGIN = re.compile(r"^<!-- generated by scripts/org-page\.py: ([a-z-]+) -->$", re.M)
END = "<!-- end generated -->"
# The Northstar picture carries the organization's tagline under its motto.
TAGLINE = "Never reached. Always pursued."
ONES = (
    "zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten",
    "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen",
    "eighteen", "nineteen",
)
TENS = ("", "", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety")


def in_words(count):
    """`count`, under a hundred, in English words: 34 is "thirty-four"."""
    if count < 20:
        return ONES[count]
    tens, ones = divmod(count, 10)
    return TENS[tens] + (f"-{ONES[ones]}" if ones else "")


NUMBERS = {in_words(count): count for count in range(100)}


def listed(items):
    """`a`, `a and b`, `a, b and c`."""
    return ", ".join(items[:-1]) + f" and {items[-1]}" if len(items) > 1 else "".join(items)


def lowered(text):
    """`text` with its first letter in lower case, unless it opens an acronym."""
    return text if text[1:2].isupper() else text[:1].lower() + text[1:]


def flat(text):
    """`text` on one line."""
    return " ".join(text.split())


def absolute(text):
    """`text` with each link to a golden-rules page made absolute."""
    return re.sub(r"\]\(([a-z]+\.md(?:#[a-z0-9-]+)?)\)", rf"]({BLOB}{RULES}/\1)", text)


def paragraph(text):
    """`text` as one Markdown paragraph wrapped at 80 columns."""
    return textwrap.fill(flat(text), 80, break_long_words=False, break_on_hyphens=False)


class Sources:
    """The golden rules, read once, and every way they disagree with themselves."""

    def __init__(self, root):
        self.root = root
        self.problems = []
        self.pages = {}
        for name in ("engineering", "security", "northstar", "standards"):
            path = root / RULES / f"{name}.md"
            if path.is_file():
                self.pages[name] = path.read_text(encoding="utf-8")
            else:
                self.pages[name] = ""
                self.refuse(f"{RULES}/{name}.md is missing")

    def refuse(self, problem):
        """Record why a source cannot be rendered."""
        self.problems.append(problem)

    def found(self, page, pattern, what, flags=re.M):
        """The first group `pattern` matches in a page, or "" and a refusal."""
        match = re.search(pattern, self.pages[page], flags)
        if match is None:
            self.refuse(f"golden-rules/{page}.md has no {what}")
            return ""
        return match.group(1)

    def rules(self, page, family):
        """(ID, title, summary) of every `### ID — Title` rule of a family."""
        found = []
        pattern = rf"^### ({family}-\d{{3}}) — ([^\n]+)\n\n((?:> [^\n]*\n)*)"
        for rule, title, quote in re.findall(pattern, self.pages[page], re.M):
            summary = flat(re.sub(r"^> ", "", quote, flags=re.M))
            if not summary:
                self.refuse(f"golden-rules/{page}.md: {rule} has no `>` summary under its "
                            f"heading")
            found.append((rule, title.strip(), summary))
        return found

    def principles(self):
        """(ID, name, meaning, non-negotiable) of every principle row."""
        rows = re.findall(r"^\| (P-\d{3}) \| ([^|]+?) \| (.+?) \|$",
                          self.pages["engineering"], re.M)
        marker = " **Non-negotiable.**"
        return [(rule, name, meaning.removesuffix(marker), meaning.endswith(marker))
                for rule, name, meaning in rows]

    def negotiable(self, page):
        """The rules a page names as the only ones that take an exception."""
        found = re.search(r"Every (?:mandate|rule) except (.+?) is \*\*non-negotiable\*\*",
                          flat(self.pages[page]))
        if found is None:
            self.refuse(f"golden-rules/{page}.md: no sentence \"Every ... except ... is "
                        f"**non-negotiable**\"")
            return []
        return re.findall(r"[A-Z]+-\d{3}", found.group(1))

    def pillars(self):
        """(pillar, what it protects) of every row of the Northstar's pillars table."""
        table = re.search(r"^## \w+ pillars\n(.*?)(?=^## )", self.pages["northstar"],
                          re.M | re.S)
        rows = re.findall(r"^\| ([A-Z][a-z]+) \| ([^|]+?) \|", table.group(1) if table else "",
                          re.M)
        return [row for row in rows if row[0] != "Pillar"]

    def standards(self):
        """(name, row) of every standard golden-rules/standards.md lists."""
        return re.findall(r"^(\| \[([^\]]+)\]\([^)]+\) \| .+ \|)$", self.pages["standards"],
                          re.M)

    def counted(self, page, noun, count):
        """Refuse every "<number in words> <noun>" of a page that is not `count`."""
        for word in re.findall(rf"\b([a-z]+(?:-[a-z]+)?) {noun}\b", self.pages[page], re.I):
            said = NUMBERS.get(word.lower())
            if said is not None and said != count:
                self.refuse(f"golden-rules/{page}.md says \"{word} {noun}\" but holds "
                            f"{count}: say \"{in_words(count)} {noun}\"")

    def check(self):
        """Every count, every mapped standard and every picture the page shows."""
        engineering = self.pages["engineering"]
        self.counted("engineering", "foundations", len(self.rules("engineering", "FND")))
        self.counted("engineering", "named principles", len(self.principles()))
        self.counted("engineering", "hard mandates", len(self.rules("engineering", "ENF")))
        adopting = len(re.findall(r"^### C-\d{3} ", engineering, re.M))
        self.counted("engineering", "rules for adopting", adopting)
        security = len(self.rules("security", "SEC"))
        self.counted("security", "security rules", security)
        heading = re.search(r"^## (\S+) rules$", self.pages["security"], re.M)
        if heading and NUMBERS.get(heading.group(1).lower()) != security:
            self.refuse(f"golden-rules/security.md: \"## {heading.group(1)} rules\" but it "
                        f"holds {security}")
        self.counted("northstar", "pillars", len(self.pillars()))
        known = {name for _, name in self.standards()}
        mapped = set()
        for page in ("engineering", "security"):
            section = re.search(r"^## Aligned with\n(.*?)(?=^## |\Z)", self.pages[page],
                                re.M | re.S)
            for name in re.findall(r"^\| ([^|\[]+?) \| .+ \|$", section.group(1) if section
                                   else "", re.M):
                if name not in ("Standard", "---"):
                    mapped.add(name)
        for name in sorted(mapped - known):
            self.refuse(f"a golden rule maps {name}, which golden-rules/standards.md does "
                        f"not list")
        for name in sorted(known - mapped):
            self.refuse(f"golden-rules/standards.md lists {name}, which no golden rule maps")
        pictures = [Path("profile/northstar.png")]
        pictures += [Path(f"profile/pillars/{pillar.lower()}.png") for pillar, _ in
                     self.pillars()]
        pictures += [Path(f"profile/foundations/{rule.lower()}.png") for rule, _, _ in
                     self.rules("engineering", "FND")]
        for picture in pictures:
            if not (self.root / picture).is_file():
                self.refuse(f"{picture} is missing: the page shows one picture for each "
                            f"pillar and foundation")


def picture(path, width, alt):
    """One centred picture of the page, served from this repository."""
    return f'  <img src="{RAW}{path}" width="{width}" alt="{alt}" />'


def northstar(sources):
    """The motto's picture, a picture per pillar and the opening paragraph."""
    quote = sources.found("northstar", r"^((?:> [^\n]*\n)+)", "opening motto")
    motto = flat(re.sub(r"^> ", "", quote, flags=re.M))
    opening = sources.found("northstar", r"^(?:> [^\n]*\n)+\n(.*?)\n\n", "opening paragraph",
                            re.M | re.S)
    pillars = sources.pillars()
    width = f"{(100 - 2 * (len(pillars) - 1)) / len(pillars):g}%"
    return "\n".join([
        '<p align="center">',
        picture("profile/northstar.png", "100%", f"Our Northstar: {lowered(motto)} {TAGLINE}"),
        "</p>",
        '<p align="center">',
        *(picture(f"profile/pillars/{name.lower()}.png", width,
                  f"Pillar {name}: {lowered(protects)}.") for name, protects in pillars),
        "</p>",
        "",
        paragraph(absolute(opening)),
        "",
        f"Read the [Northstar]({BLOB}{RULES}/northstar.md) in full.",
    ])


def foundations(sources):
    """A picture per foundation, two to a row."""
    rows = []
    rules = sources.rules("engineering", "FND")
    for start in range(0, len(rules), 2):
        rows.append('<p align="center">')
        for rule, title, summary in rules[start:start + 2]:
            number = int(rule.split("-")[1])
            alt = f"Foundation {number:02d}, {lowered(title)}: {lowered(summary)}"
            rows.append(picture(f"profile/foundations/{rule.lower()}.png", "49%", alt))
        rows.append("</p>")
    return "\n".join(rows)


def folded(count, noun, tagline, header, rows, after=()):
    """A folded table: its count and noun, a tagline, then one row per rule."""
    return "\n".join([
        "<details>",
        f"<summary><strong>{in_words(count).capitalize()} {noun}</strong>: "
        f"{tagline}</summary>",
        "",
        f"| {header} | In one line |" if header != "Principle" else
        "| Principle | What it means |",
        "| --- | --- |",
        *(f"| **{title}**<br>`{rule}` | {line.removesuffix('.')} |" for rule, title, line in rows),
        "",
        *after,
        "</details>",
    ])


def exceptions(rules):
    """The tagline of a family where only `rules` take an exception."""
    return f"all non-negotiable but {listed(rules)}" if rules else "all non-negotiable"


def mandates(sources):
    """The hard mandates, each with its summary."""
    rules = [(rule, title, summary) for rule, title, summary in
             sources.rules("engineering", "ENF")]
    return folded(len(rules), "hard mandates", exceptions(sources.negotiable("engineering")),
                  "Mandate", rules)


def security(sources):
    """The security rules, each with its summary."""
    rules = sources.rules("security", "SEC")
    return folded(len(rules), "security rules", exceptions(sources.negotiable("security")),
                  "Rule", rules)


def principles(sources):
    """The named principles, each with what it means."""
    rows = sources.principles()
    strict = [rule for rule, _, _, hard in rows if hard]
    tagline = f"{listed(strict)} are non-negotiable" if strict else "none is non-negotiable"
    return folded(len(rows), "named principles", tagline, "Principle",
                  [(rule, name, meaning) for rule, name, meaning, _ in rows])


def gate_rules(_):
    """The rules the shared CI refuses, as the latest release lists them."""
    listing = subprocess.run(["rust-gate", "gate-rules"], capture_output=True, text=True,
                             check=True).stdout
    rules = [line.split("\t") for line in listing.splitlines()]
    excepted = [rule for rule, _, kind, _ in rules if kind == "exception"]
    note = paragraph(f"Only {listed(excepted)} take an exception, recorded with its reason "
                     f"in the repository's `maestro-quality.toml`; an exception that stops "
                     f"being true fails the check.")
    return folded(len(rules), "gate rules", "what the shared CI refuses on every pull "
                  "request, most of them already at commit", "Rule",
                  [(rule, name, holds) for rule, name, _, holds in rules], [note, ""])


def standards(sources):
    """What golden-rules/standards.md says, then its table."""
    opening = sources.found("standards", r"^# .+\n\n(.*?)\n\n", "opening paragraph",
                            re.M | re.S)
    return "\n".join([
        paragraph(absolute(opening)),
        "",
        "| Standard | Version | What it covers |",
        "| --- | --- | --- |",
        *(row for row, _ in sources.standards()),
    ])


def repositories(_):
    """Every public repository but this one, with the description GitHub shows."""
    pages = json.loads(subprocess.run(
        ["gh", "api", "--paginate", "--slurp", f"orgs/{ORG}/repos?per_page=100"],
        capture_output=True, text=True, check=True).stdout)
    shown = sorted((repo["name"], repo.get("description") or "No description on GitHub yet")
                   for page in pages for repo in page
                   if repo["visibility"] == "public" and not repo["archived"]
                   and repo["name"] != ".github")
    return "\n".join([
        "| Repository | What it is |",
        "| --- | --- |",
        *(f"| [{name}](https://github.com/{ORG}/{name}) | {description.removesuffix('.')} |"
          for name, description in shown),
    ])


BLOCKS = {
    "northstar": northstar,
    "foundations": foundations,
    "mandates": mandates,
    "security": security,
    "principles": principles,
    "gate-rules": gate_rules,
    "standards": standards,
    "repositories": repositories,
}


def rendered(text, sources):
    """`text` with every generated block rewritten from its source."""
    names = BEGIN.findall(text)
    for name in BLOCKS:
        if names.count(name) != 1:
            sys.exit(f"{PAGE}: the {name} block appears {names.count(name)} times; put "
                     f"`<!-- generated by scripts/org-page.py: {name} -->` and `{END}` "
                     f"around it once")
    out, position = [], 0
    for begin in BEGIN.finditer(text):
        name = begin.group(1)
        if name not in BLOCKS:
            sys.exit(f"{PAGE}: unknown generated block {name}")
        end = text.find(END, begin.end())
        out += [text[position:begin.end()], "\n", BLOCKS[name](sources), "\n"]
        position = end
    return "".join(out) + text[position:]


def main():
    parser = argparse.ArgumentParser(description="Write the organization page's blocks.")
    parser.add_argument("--check", action="store_true", help="write nothing; exit 1 when stale")
    parser.add_argument("--root", type=Path, default=Path("."), help="the repository's root")
    arguments = parser.parse_args()
    page = arguments.root / PAGE
    if not page.is_file():
        return
    sources = Sources(arguments.root)
    if sources.problems:
        sys.exit("golden rules: " + "; ".join(sources.problems))
    sources.check()
    if sources.problems:
        sys.exit("golden rules: " + "; ".join(sources.problems))
    text = page.read_text(encoding="utf-8")
    new = rendered(text, sources)
    if sources.problems:
        sys.exit("golden rules: " + "; ".join(sources.problems))
    if arguments.check:
        if new != text:
            sys.exit(f"{PAGE}: a generated block differs from its source; run "
                     f"scripts/org-page.py")
        return
    if new != text:
        page.write_text(new, encoding="utf-8")
        print(f"wrote {PAGE}")


if __name__ == "__main__":
    main()
